// Generated by CoffeeScript 1.6.3
(function() {
  var URI, URICollection, assert, isURI, _ref;

  assert = require("better-assert");

  _ref = require("../index.js"), URICollection = _ref.URICollection, isURI = _ref.isURI;

  URI = require("URIjs");

  describe("isURI", function() {
    it("should return true for URI instances.", function() {
      var aLink;
      aLink = new URI("http://www.google.com");
      return assert(isURI(aLink) === true);
    });
    it("should not return true for strings.", function() {
      var aLink;
      aLink = "http://www.google.com";
      return assert(isURI(aLink) === false);
    });
    return it("should not return true for other constructed objects.", function() {
      var Barly, bar;
      Barly = function() {
        return this.fluxom = "zabberjabber";
      };
      Barly.prototype.doSomething = function() {
        return 17;
      };
      bar = new Barly();
      return assert(isURI(bar) === false);
    });
  });

}).call(this);
