// Generated by CoffeeScript 1.6.3
(function() {
  var URI, URICollection, URLCOUNT, URL_INDICES, assert, isURI, urlList, _, _i, _ref, _ref1, _results;

  assert = require("better-assert");

  _ = require("underscore");

  _ref = require("../index.js"), URICollection = _ref.URICollection, isURI = _ref.isURI;

  URI = require("URIjs");

  urlList = ["http://www.google.com/foo", "http://www.cnn.com/theNewsIGuess", "http://www.foo.com/index.html"];

  URLCOUNT = urlList.length;

  URL_INDICES = (function() {
    _results = [];
    for (var _i = 0, _ref1 = URLCOUNT - 1; 0 <= _ref1 ? _i <= _ref1 : _i >= _ref1; 0 <= _ref1 ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this);

  describe("URICollection", function() {
    var collection, _urls;
    _urls = _.clone(urlList);
    collection = {};
    beforeEach(function() {
      return collection = new URICollection(_urls);
    });
    describe("map", function() {
      it("should return a new URICollection when a map operation returns URIjs instances.", function() {
        var _mapped;
        _mapped = collection.map(function(uri) {
          return uri.domain("jabber.net");
        });
        return assert(_mapped instanceof URICollection);
      });
      it("should return a vanilla array when a map operation returns results other than URIjs instances.", function() {
        var _mapped;
        _mapped = collection.map(function(uri) {
          return uri.domain();
        });
        return assert(_mapped instanceof Array);
      });
      it("should not mutate URIjs instances in the original collection", function() {
        var copy, i, _j, _len, _mapped, _results1;
        copy = collection.clone();
        _mapped = copy.map(function(uri) {
          return uri.domain("changed.net");
        });
        _results1 = [];
        for (_j = 0, _len = URL_INDICES.length; _j < _len; _j++) {
          i = URL_INDICES[_j];
          assert(copy.stringAt(i) === collection.stringAt(i));
          _results1.push(assert(_mapped.stringAt(0) !== collection.stringAt(0)));
        }
        return _results1;
      });
      return it("should produce the same result as a series of individual URIjs instance manipulations.", function() {
        var copy, i, _j, _len, _mapped, _results1;
        copy = collection.clone();
        _mapped = copy.map(function(uri) {
          return uri.domain("changed.net");
        });
        _results1 = [];
        for (_j = 0, _len = URL_INDICES.length; _j < _len; _j++) {
          i = URL_INDICES[_j];
          _results1.push(assert(_mapped.stringAt(i) === collection.at(i).clone().domain("changed.net").toString()));
        }
        return _results1;
      });
    });
    describe("toArray", function() {
      it("should return a vanilla javascript array", function() {
        return assert(collection.toArray() instanceof Array);
      });
      return it("should return *clones* of its internal URIjs instances", function() {
        var fromCollection, i, _j, _len, _results1;
        fromCollection = collection.toArray();
        _results1 = [];
        for (_j = 0, _len = URL_INDICES.length; _j < _len; _j++) {
          i = URL_INDICES[_j];
          assert(fromCollection[i] !== collection.at(i));
          assert(fromCollection[i].toString() === collection.at(i).toString());
          _results1.push(assert(fromCollection[i].domain("other.org").toString() !== collection.at(i).toString()));
        }
        return _results1;
      });
    });
    describe("clone", function() {
      it("should return a new URICollection instance", function() {
        return assert(collection.clone() instanceof URICollection);
      });
      it("should create a copy with the same number of elements", function() {
        return assert(collection.clone().size() === collection.size());
      });
      it("should create a copy with individual URIjs elements cloned themselves", function() {
        var cloned, i, _j, _len, _results1;
        cloned = collection.clone();
        _results1 = [];
        for (_j = 0, _len = URL_INDICES.length; _j < _len; _j++) {
          i = URL_INDICES[_j];
          _results1.push(assert(cloned.at(i) !== collection.at(i)));
        }
        return _results1;
      });
      return it("should create a copy with DEEP-equal elements", function() {
        var cloned, i, _j, _len, _results1;
        cloned = collection.clone();
        _results1 = [];
        for (_j = 0, _len = URL_INDICES.length; _j < _len; _j++) {
          i = URL_INDICES[_j];
          _results1.push(assert(cloned.at(i).toString() === collection.at(i).toString()));
        }
        return _results1;
      });
    });
    return describe("each", function() {
      it("should return a new URI collection, even without an iterator return value", function() {
        var eachified;
        eachified = collection.each(function(x) {
          return x;
        });
        assert(eachified instanceof URICollection);
        return assert(eachified.size() === collection.size());
      });
      it("should not mutate URIjs instances in the original collection", function() {
        var copy, eachified, i, _j, _len, _results1;
        copy = collection.clone();
        eachified = copy.each(function(uri) {
          return uri.domain("changed.net");
        });
        _results1 = [];
        for (_j = 0, _len = URL_INDICES.length; _j < _len; _j++) {
          i = URL_INDICES[_j];
          assert(copy.stringAt(i) === collection.stringAt(i));
          _results1.push(assert(eachified.stringAt(0) !== collection.stringAt(0)));
        }
        return _results1;
      });
      return it("should produce the same result as a series of individual URIjs instance manipulations.", function() {
        var copy, eachified, i, _j, _len, _results1;
        copy = collection.clone();
        eachified = copy.each(function(uri) {
          return uri.domain("changed.net");
        });
        _results1 = [];
        for (_j = 0, _len = URL_INDICES.length; _j < _len; _j++) {
          i = URL_INDICES[_j];
          _results1.push(assert(eachified.stringAt(i) === collection.at(i).clone().domain("changed.net").toString()));
        }
        return _results1;
      });
    });
  });

}).call(this);
